version: "3.8"

services:
  postgres:
    container_name: postgres-fast-api
    image: postgres:latest
    env_file:
      - ./dotfiles/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - fast-api-network

  fastapi:
    container_name: fast-api-demo
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - fast-api-network

volumes:
  postgres_data:

networks:
  fast-api-network:
