services:
  postgres:
    restart: always
    container_name: postgres-fast-api
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d fast-api-db"]
      interval: 3s
      timeout: 5s
      retries: 5
    env_file:
      - ./dotfiles/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - fast-api-network

  fastapi:
    container_name: fast-api-demo
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - fast-api-network

volumes:
  postgres_data:

networks:
  fast-api-network:
